name: Déploiement sur AlwaysData

on:
  push:
    branches:
      - main  # Déclenche le workflow à chaque push sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Déployer via SFTP
        uses: appleboy/scp-action@master
        with:
          host: "ssh-departementinfoaix.alwaysdata.net"
          username: "departementinfoaix"
          key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
          source: "."  # Fichiers à envoyer (".": tout envoyer)
          target: "/home/departementinfoaix/www/"  # Dossier cible sur AlwaysData

      - name: Exécuter des commandes sur AlwaysData (si besoin)
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-departementinfoaix.alwaysdata.net"
          username: "departementinfoaix"
          key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
          script: |
            cd /home/departementinfoaix/www/
            composer update