name: Déploiement sur AlwaysData

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Déployer via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALWAYSDATA_HOST }}
          username: ${{ secrets.ALWAYSDATA_USER }}
          password: ${{ secrets.ALWAYSDATA_MDP }}
          key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
          source: "./src/ ./public/ ./vendor/ ./env ./composer.json ./composer.lock"
          target: ${{ secrets.ALWAYSDATA_PATH }}
          strip_components: 1

      - name: Exécuter des commandes sur AlwaysData (si besoin)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALWAYSDATA_HOST }}
          username: ${{ secrets.ALWAYSDATA_USER }}
          password: ${{ secrets.ALWAYSDATA_MDP }}
          key: ${{ secrets.ALWAYSDATA_SSH_KEY }}
          script: |
            cd ${{ secrets.ALWAYSDATA_PATH }}
            composer update
